language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "ryI8WnpPdVX5DhBwJLyYnal6RY0Yg+4l5K0mmFf+iyCpk44xNUBkpdWEcQUskz9anPjaXZIrKuE9cGliBUE3WCNNn3tUIQRDLP8fgzK1WkuHMYFhT+2FbBM3/cC0n5kop1AvydGdXp4oPsAUIXzp7W0POzBsBCkbqaEeYjLykBZdqePPT0MTZkde5c6Hxzbpw91gHvd8Aoyimtj3uiWETDuMxPYICEJirXr/DXfNSsdEpT00nFletU+cq3Jx1TFxZiPP8Z2g9vWhd1B6uR/+JbdRyfAz7VxGX90EUIRwBrlYL80Nft0hQwZUurwg6+SUTBpUKVfQ6s3lq8+XwVqx6k7SZt7F2u3M5coHuwcEXPA0YA4uQHlQwUFjhpD97PGlWTAbmRcpIQ2DpYhKqmTA8GckwtYskF8NZoRPZhKHHT+B9dcIDTLg4rA3mghCi1uHmZn/LHDlH3fRHA3UTfDr02XODXTbApRr/3i/qxilYHiOnPFKhHXsovmykqw4HBGuWGrfflNAKqsLXRPp73wyKWf4KUJVIFWCGKNr2Lb8DXYwoWjjswwMAJ61uAzfNYfTjEpINcgSCDKb87975Uwf3qw3ZzvlbftSnh8uDGLyVMGY0+P5R3JaBM5zXDFuKrIjbcxamfn2iddmEGsDHZ55ya6lx/CJV6YlWFmF6YAbUiI="
